info:
  name: swagger ui
  type: http
  seq: 4

http:
  method: GET
  url: http://localhost:8080/swagger-ui/index.html
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
