info:
  name: swagger yaml
  type: http
  seq: 3

http:
  method: GET
  url: http://localhost:8080/openapi/swagger.yaml
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
